spring:
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
mybatis-plus:
  mapper-locations: classpath:cn/gnaixeuy/redbook/dao/impl/*.xml
  type-aliases-package: cn.gnaixeuy.redbook.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_uuid
      table-underline: true
fdfs:
  soTimeout: 15000  # 读取时间
  connectTimeout: 15000  # 链接超时
  pool:
    max-total: 200   # 连接池最大数量
    max-total-per-key: 50  # 单个tracker最大连接数
    max-wait-millis: 5000 # 连接耗尽最大等待时间 毫秒
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  #  tracker-list:
