spring:
  banner:
    location: banner.txt
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
  redis:
    host: localhost
    port: 6379
    password:
    dbs: 0,1,3,5
mybatis-plus:
  mapper-locations: classpath:cn/gnaixeuy/redbook/dao/impl/*.xml
  type-aliases-package: cn.gnaixeuy.redbook.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_uuid
      table-underline: true
fdfs:
  soTimeout: 15000  # 读取时间
  connectTimeout: 15000  # 链接超时
  pool:
    max-total: 200   # 连接池最大数量
    max-total-per-key: 50  # 单个tracker最大连接数
    max-wait-millis: 5000 # 连接耗尽最大等待时间 毫秒
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  #  tracker-list:
#  aliyun:
#    accessKeyId:
#    secret:

netty:
  websocket:
    # Websocket服务端口
    port: 1024
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
    max-frame-size: 10240
    # URI路径
    path: /channel

phone:
  verification:
    length: 6
    live: 300